#!/bin/bash

LEVEL=$(acpi -b | grep -v "unavailable" | cut -d ' ' -f4 | cut -d '%' -f1)

BICON=' '
[[ $LEVEL -le 90 ]] && BICON=' '
[[ $LEVEL -le 60 ]] && BICON=' '
[[ $LEVEL -le 30 ]] && BICON=' '
acpi -a | grep -i "on-line" > /dev/null
if [ $? -eq 0 ]; then 
	PLUGGED=' '
fi

echo $PLUGGED $BICON $LEVEL%

