#!/bin/bash

set -e

BATTERY=$(dualsensectl battery | cut -d " " -f1)

case "$BLOCK_BUTTON" in
	1) 
		CLICKED=$(dunstify --action="dualsensectl power-off,dualsensectl power-off" "Turn off Controller?" )
		if [[ $CLICKED == "dualsensectl power-off" ]];then
			dualsensectl power-off
		fi
		;;
esac

	if [ ! -z $BATTERY ]; then
		echo "  $BATTERY%"
		echo "  $BATTERY%"
	fi
