#!/bin/bash

ARTIST=$(playerctl --ignore-player=firefox metadata artist)
TITLE=$(playerctl --ignore-player=firefox metadata title)
MVOL=$(pamixer --sink music --get-volume)

VICON=' '
[[ $MVOL -le 40 ]] && VICON=' '
[[ $MVOL -le 0 ]] && VICON=' '

STATUS=$(playerctl --ignore-player=firefox status)
if [ "$STATUS" = "Playing" ]; then 
	echo "$VICON $MVOL% $ARTIST - $TITLE"
	echo "$VICON $MVOL% $ARTIST - $TITLE"
else
	echo "$VICON $MVOL% Media Paused"
	echo "$VICON $MVOL% Media Paused"
	echo "#a0a0a0"
fi

	
