#!/bin/bash
case $button in
	1)
		i3-msg exec -q "i3-dd Spotify"
		;;
	3)
		i3-msg exec -q "playerctl --ignore-player=firefox play-pause"
		sleep 0.1
		;;
	4)
		i3-msg exec -q "pamixer --sink music -i 1"
		;;
	5)
		i3-msg exec -q "pamixer --sink music -d 1"
		;;
	6)
		i3-msg exec -q "playerctl --ignore-player=firefox previous"
		;;
	7)
		i3-msg exec -q "playerctl --ignore-player=firefox next"
		;;
esac

ARTIST=$(playerctl --ignore-player=firefox metadata artist)
TITLE=$(playerctl --ignore-player=firefox metadata title)
MVOL=$(pactl list sink-inputs | grep -B25 Spotify | grep Volume | cut -d "/" -f2 | xargs | cut -d "%" -f1)

VICON='󰎈'
[[ $MVOL -le 40 ]] && VICON='󰎈'
[[ $MVOL -le 0 ]] && VICON='󰎊'

STATUS=$(playerctl --ignore-player=firefox status)
if [ "$STATUS" = "Playing" ]; then 
	echo "$VICON $MVOL% $ARTIST - $TITLE"
	echo "$VICON $MVOL% $ARTIST - $TITLE"
else
	echo "$VICON $MVOL% Media Paused"
	echo "$VICON $MVOL% Media Paused"
	echo "#a0a0a0"
fi

