#!/bin/zsh
case "$BLOCK_BUTTON" in
	*)
		dunstify -r 9814 "Checking For Updates!"
		;;
esac

updates=$(sort <<< $(checkupdates) $(yay -Qum))

if [ "
" = "$updates" ]; then
	count=$(wc -l <<< $updates)
else
	count=0
fi
 
if [ $count -gt 0 ]; then
	echo "$count updates"
else
	echo "No Updates"
fi

case "$BLOCK_BUTTON" in
	*)
		if [ $count -gt 0 ]; then
			ACTION=$(dunstify -r 9814 --action="default,listUpdates" "Found $count Updates")
		else
			dunstify -r 9814 "System is up to date"
		fi

		case "$ACTION" in 
			"default")
				kitty --class k_checkupdates --hold zsh -c "echo '$updates'"
		esac
esac

if [ $count -gt 100 ]; then
	exit 33
fi
