#!/bin/zsh
if [[ -v BLOCK_BUTTON ]]; then
	dunstify -r 9814 "Checking For Updates!"
fi

updates=$(sort <<< $(checkupdates) $(yay -Qum))

if [ "
" = "$updates" ]; then
	count=$(wc -l <<< $updates)
else
	count=0
fi
 
if [ $count -gt 0 ]; then
	echo "$count updates"
else
	echo "No Updates"
fi

if [[ -v BLOCK_BUTTON ]]; then
	if [ $count -gt 0 ]; then
		ACTION=$(dunstify -r 9814 --action="default,listUpdates" "Found $count Updates")
	else
		dunstify -r 9814 "System is up to date"
	fi

	case "$ACTION" in 
		"default")
			kitty --class k_checkupdates --hold zsh -c "echo '$updates'"
	esac
fi

if [ $count -gt 100 ]; then
	exit 33
fi
