#!/usr/bin/bash

case "$BLOCK_BUTTON" in
    1) i3-msg exec pavucontrol > /dev/null;;
    2) pamixer -t ;;
    4) pamixer -i 1 ;;
    5) pamixer -d 1 ;;
esac

VOL=$(pamixer --get-volume)

ICON=
[[ $VOL -le 45 ]] && ICON=
[[ $VOL -le 20 ]] && ICON=

echo "$ICON $VOL%"
echo "$ICON $VOL%"


[ "$(pamixer --get-mute)" == "true" ] && echo "#a0a0a0"

